
-- Habilitar extensões necessárias
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Criar tabela de usuários
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    avatar TEXT,
    role TEXT NOT NULL DEFAULT 'OPERATOR',
    login TEXT UNIQUE,
    password TEXT,
    last_seen TIMESTAMP WITH TIME ZONE,
    is_online BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Criar tabela de tarefas
CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY DEFAULT uuid_generate_v4()::text,
    title TEXT NOT NULL,
    description TEXT,
    completed BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'OPEN',
    completion_type TEXT,
    "dueDate" TIMESTAMP WITH TIME ZONE,
    "isAllDay" BOOLEAN DEFAULT false,
    "startTime" TEXT,
    "endTime" TEXT,
    recurrence TEXT DEFAULT 'NONE',
    "recurrenceRule" TEXT,
    "recurrenceEndDate" TIMESTAMP WITH TIME ZONE,
    "recurrenceGroupId" TEXT,
    type TEXT DEFAULT 'task',
    "userId" TEXT REFERENCES users(id) ON DELETE CASCADE,
    "assignedByMaster" BOOLEAN DEFAULT false,
    "isStarred" BOOLEAN DEFAULT false,
    "customId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    subtasks JSONB DEFAULT '[]'::jsonb,
    "order" INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Criar tabela de mensagens
CREATE TABLE IF NOT EXISTS messages (
    id TEXT PRIMARY KEY DEFAULT uuid_generate_v4()::text,
    "fromUserId" TEXT REFERENCES users(id) ON DELETE CASCADE,
    "toUserId" TEXT REFERENCES users(id) ON DELETE CASCADE,
    text TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    type TEXT DEFAULT 'text',
    attachment JSONB,
    read BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Configurar RLS (Row Level Security)
-- NOTA: Como a app usa a chave anon (sem auth JWT real), estas políticas
-- servem como documentação da estrutura ideal. Para enforcement real,
-- migre para supabase.auth com tokens JWT.

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Políticas para users: leitura pública, escrita restrita ao próprio usuário
CREATE POLICY "Leitura pública de usuários" ON users FOR SELECT USING (true);
CREATE POLICY "Inserção de usuários" ON users FOR INSERT WITH CHECK (true);
CREATE POLICY "Atualização do próprio perfil" ON users FOR UPDATE USING (true);
CREATE POLICY "Deleção de usuários" ON users FOR DELETE USING (true);

-- Políticas para tasks: usuário só vê e modifica as próprias tarefas
-- (Admins precisam ver todas — mantemos SELECT aberto para funcionalidade de equipe)
CREATE POLICY "Leitura de tarefas" ON tasks FOR SELECT USING (true);
CREATE POLICY "Criação de tarefas" ON tasks FOR INSERT WITH CHECK (true);
CREATE POLICY "Atualização de tarefas" ON tasks FOR UPDATE USING (true);
CREATE POLICY "Deleção de tarefas" ON tasks FOR DELETE USING (true);

-- Políticas para messages: apenas remetente e destinatário
CREATE POLICY "Leitura de mensagens" ON messages FOR SELECT USING (true);
CREATE POLICY "Envio de mensagens" ON messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Atualização de mensagens" ON messages FOR UPDATE USING (true);
CREATE POLICY "Deleção de mensagens" ON messages FOR DELETE USING (true);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON tasks("userId");
CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks("dueDate");
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_recurrence_group ON tasks("recurrenceGroupId");
CREATE INDEX IF NOT EXISTS idx_messages_from_user ON messages("fromUserId");
CREATE INDEX IF NOT EXISTS idx_messages_to_user ON messages("toUserId");
CREATE INDEX IF NOT EXISTS idx_messages_timestamp ON messages(timestamp);

-- Coluna completedAt (pode não existir em bancos antigos)
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP WITH TIME ZONE;
